### ISSUE TITLE
No rescheduling with addon

### ISSUE THREAD

**Issue by bongobong22** [is343/anki_delay_deck#4] opened 2019-03-14 13:10 UTC
Hello, 

Your addon is really interesting.
However, it doesn't work on my anki app. When i'm clicking on the icon "delay overdue" it doesn't detect overdue of my deck. When i'm trying to choose manually how many days i want to rescheduling my deck, nothing is happening. 

Thank You :)

**Comment by is343** [comment] 2019-03-14 13:43
Hello! Thanks for bringing this to my attention. 
Does this happen to every deck, or is it just happening with one particular deck?

If possible, can you provide a sample deck that isn't working so I can check it out?

**Comment by bongobong22** [comment] 2019-03-14 14:13
It's happen with every deck.

Of course, here is a deck with 1 day late 
https://drive.google.com/file/d/1qd_Y509Pw2TOksjTbHQsqZfE2l9_YQIY/view?usp=sharing

**Comment by is343** [comment] 2019-03-14 14:45
Aha! 
Thank you for for supplying the deck!

I think it's because you have nested decks. If you expand the decks, you should be able to delay each one separately.

I had never used nested decks like this, so I had never considered testing for this. It is 11:42 PM for me here, so I will try working on a fix for this issue tomorrow. 

I'm sorry for the inconvenience. I will try to get this issue fixed as quickly as possible.
For right now, what you can do is delay the nested decks separately. 

For example, **_Médecine_** and **_Néphrologie/Uro_** don't work.
But _**Troubles de la miction**_ _does_.

Thanks again for bringing this to my attention!

![image](https://user-images.githubusercontent.com/30599893/54365563-65f21e00-46b2-11e9-95ce-34819a3271f7.png)

**Comment by johnnyjohnjohnjohn** [comment] 2020-08-15 14:34
The problem is definitely nested decks. I appreciate your assistance. 

Question: Is it possible to update the add-on so that it does work with nested decks? Some decks, like lolnotacop and Zanki Step Decks are HUUUUUUUGE decks with lots of nested subdecks. It would make life a whole lot easier if we could use this great app on the parent and it works for all the subdecks below. THANK YOU!

**Comment by is343** [comment] 2020-08-16 21:57
@johnnyjohnjohnjohn @bongobong22 Hello! Thank you for bringing this back to my attention! I apologize for the delay, I have just been so busy so I haven't been able to dive into this issue.
I spent the day debugging and figured the issue out. 

I have updated the plugin on AnkiWeb and you are now able to delay nested decks by clicking on the parent deck.

**Closed as completed by is343** 2020-08-16 21:57 UTC
Labels: bug, help wanted
